<?php

namespace Protector\AppBundle\Repository;

/**
 * GeneratedLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneratedLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
